import Foundation

public extension String {
  func localized(for locale: Locale) -> String {
    let languageCode = locale.language.languageCode?.identifier ?? "en"
    
    // Custom translations map
    let translations: [String: [String: String]] = [
      "divine_self": [
        "en": "Divine Self", 
        "ru": "Божественное Я",
        "uk": "Божественне Я",
        "es": "Yo Divino",
        "pt": "Eu Divino",
        "fr": "Soi Divin",
        "de": "Göttliches Selbst",
        "it": "Sé Divino",
        "pl": "Boska Jaźń",
        "tr": "İlahi Benlik",
        "zh": "神圣自我",
        "ja": "神聖なる自己",
        "ko": "신성한 자아",
        "hi": "दिव्य स्व",
        "bn": "দিব্য সত্তা"
      ],
      "essential_self": [
        "en": "Essential Self",
        "ru": "Сущностное Я",
        "uk": "Сутнісне Я",
        "es": "Yo Esencial",
        "pt": "Eu Essencial",
        "fr": "Soi Essentiel",
        "de": "Essenzielles Selbst",
        "it": "Sé Essenziale",
        "pl": "Istotowa Jaźń",
        "tr": "Özsel Benlik",
        "zh": "本质自我",
        "ja": "本質の自己",
        "ko": "본질 자아",
        "hi": "सारभूत स्व",
        "bn": "সারসত্তা"
      ],
      "settings": [
        "en": "Settings",
        "ru": "Настройки", 
        "uk": "Налаштування",
        "es": "Ajustes",
        "pt": "Ajustes",
        "fr": "Réglages",
        "de": "Einstellungen",
        "it": "Impostazioni",
        "pl": "Ustawienia",
        "tr": "Ayarlar",
        "zh": "设置",
        "ja": "設定",
        "ko": "설정",
        "hi": "सेटिंग",
        "bn": "সেটিংস"
      ],
      "sound": [
        "en": "Sound",
        "ru": "Звук",
        "uk": "Звук",
        "es": "Sonido",
        "pt": "Som",
        "fr": "Son",
        "de": "Ton",
        "it": "Suono",
        "pl": "Dźwięk",
        "tr": "Ses",
        "zh": "声音",
        "ja": "サウンド",
        "ko": "사운드",
        "hi": "ध्वनि",
        "bn": "শব্দ"
      ],
      "duration": [
        "en": "Duration",
        "ru": "Длительность",
        "uk": "Тривалість",
        "es": "Duración",
        "pt": "Duração",
        "fr": "Durée",
        "de": "Dauer",
        "it": "Durata",
        "pl": "Czas trwania",
        "tr": "Süre",
        "zh": "时长",
        "ja": "長さ",
        "ko": "길이",
        "hi": "अवधि",
        "bn": "সময়কাল"
      ],
      "language": [
        "en": "Language",
        "ru": "Язык",
        "uk": "Мова",
        "es": "Idioma",
        "pt": "Idioma",
        "fr": "Langue",
        "de": "Sprache",
        "it": "Lingua",
        "pl": "Język",
        "tr": "Dil",
        "zh": "语言",
        "ja": "言語",
        "ko": "언어",
        "hi": "भाषा",
        "bn": "ভাষা"
      ],
      "min": [
        "en": "min",
        "ru": "мин",
        "uk": "хв",
        "es": "min",
        "pt": "min",
        "fr": "min",
        "de": "Min.",
        "it": "min",
        "pl": "min",
        "tr": "dk",
        "zh": "分钟",
        "ja": "分",
        "ko": "분",
        "hi": "मि.",
        "bn": "মি."
      ],
      "en": [
        "en": "English",
        "ru": "Английский",
        "uk": "Англійська"
      ],
      "uk": [
        "en": "Ukrainian",
        "ru": "Украинский",
        "uk": "Українська"
      ],
      "ru": [
        "en": "Russian",
        "ru": "Русский",
        "uk": "Російська"
      ],
      "step1": [
        "en": "Ask permission to speak with the Lords of Karma.",
        "ru": "Спросите разрешения поговорить с Властителями Кармы.",
        "uk": "Запитайте дозвіл говорити з Володарями Карми.",
        "es": "Pide permiso para hablar con los Señores del Karma.",
        "pt": "Peça permissão para falar com os Senhores do Karma.",
        "fr": "Demandez la permission de parler aux Seigneurs du Karma.",
        "de": "Bitte um Erlaubnis, mit den Herren des Karma zu sprechen.",
        "it": "Chiedi il permesso di parlare con i Signori del Karma.",
        "pl": "Poproś o pozwolenie na rozmowę z Władcami Karmy.",
        "tr": "Karma Efendileri ile konuşmak için izin iste.",
        "zh": "请求与业力之主交谈的许可。",
        "ja": "カルマの主たちと話す許可を求めます。",
        "ko": "카르마의 주인들과 이야기할 허락을 구하세요.",
        "hi": "कर्म के स्वामियों से बात करने की अनुमति माँगें।",
        "bn": "কর্মের অধিপতিগণের সঙ্গে কথা বলার অনুমতি চান।"
      ],
      "step2": [
        "en": "Ask them to align your energy bodies and set up contacts between them.",
        "ru": "Попросите их выстроить ваши энергетические тела и настроить контакты между ними",
        "uk": "Попросіть їх вирівняти ваші енергетичні тіла та налаштувати контакти між ними.",
        "es": "Pídeles que alineen tus cuerpos energéticos y establezcan los contactos entre ellos.",
        "pt": "Peça que eles alinhem seus corpos energéticos e estabeleçam os contatos entre eles.",
        "fr": "Demandez-leur d'aligner vos corps énergétiques et d'établir les contacts entre eux.",
        "de": "Bitte sie, deine Energiekörper auszurichten und die Verbindungen zwischen ihnen herzustellen.",
        "it": "Chiedi loro di allineare i tuoi corpi energetici e di stabilire i contatti tra di essi.",
        "pl": "Poproś ich o wyrównanie Twoich ciał energetycznych i ustanowienie połączeń między nimi.",
        "tr": "Onlardan enerji bedenlerini hizalamasını ve aralarındaki bağlantıları kurmasını iste.",
        "zh": "请他们校准你的各个能量体，并建立彼此之间的连接。",
        "ja": "エネルギー体を整え、それぞれのあいだのつながりを結ぶよう願い出ます。",
        "ko": "에너지체들을 정렬하고 그 사이의 연결을 세워 달라고 청하세요.",
        "hi": "उनसे प्रार्थना करें कि वे आपके ऊर्जा शरीरों को संरेखित करें और उनके बीच संपर्क स्थापित करें।",
        "bn": "তাঁদের বলুন আপনার শক্তিদেহগুলি সারিবদ্ধ করতে এবং সেগুলির মধ্যে সংযোগ স্থাপন করতে।"
      ],
      "step3": [
        "en": "Ask to clear, heal, activate and open:",
        "ru": "Попросите очистить, исцелить, активировать и открыть:",
        "uk": "Попросіть очистити, зцілити, активувати та відкрити:",
        "es": "Pide que se limpien, sanen, activen y abran:",
        "pt": "Peça para limpar, curar, ativar e abrir:",
        "fr": "Demandez le nettoyage, la guérison, l'activation et l'ouverture de :",
        "de": "Bitte um Reinigung, Heilung, Aktivierung und Öffnung von:",
        "it": "Chiedi di purificare, guarire, attivare e aprire:",
        "pl": "Poproś o oczyszczenie, uzdrowienie, aktywację i otwarcie:",
        "tr": "Şunların arındırılmasını, iyileştirilmesini, etkinleştirilmesini ve açılmasını iste:",
        "zh": "请求清理、疗愈、激活并打开：",
        "ja": "次のものの浄化・癒やし・活性化・開放を願い出ます：",
        "ko": "다음의 정화와 치유, 활성화와 열림을 청하세요:",
        "hi": "इन्हें शुद्ध करने, उपचारित करने, सक्रिय करने और खोलने की प्रार्थना करें:",
        "bn": "এগুলি শুদ্ধ, নিরাময়, সক্রিয় ও উন্মুক্ত করার প্রার্থনা করুন:"
      ],
      "step3text": [
        "en": "a) Ka Matrix;\nb) Etheric Matrix;\nc) Ketheric Matrix;\nd) Celestial Matrix;\nd) I-Am Matrix.",
        "ru": "а) Матрицу Ка;\nb) Эфирную Матрицу;\nc) Кетерическую Матрицу;\nd) Небесную Матрицу;\nd) Матрицу Я-Есть.",
        "uk": "а) Матрицю Ка;\nb) Ефірну Матрицю;\nc) Кетеричну Матрицю;\nd) Небесну Матрицю;\nd) Матрицю Я-Є.",
        "es": "a) la Matriz Ka;\nb) la Matriz Etérica;\nc) la Matriz Ketérica;\nd) la Matriz Celestial;\nd) la Matriz Yo Soy.",
        "pt": "a) a Matriz Ka;\nb) a Matriz Etérica;\nc) a Matriz Ketérica;\nd) a Matriz Celestial;\nd) a Matriz Eu Sou.",
        "fr": "a) la Matrice Ka ;\nb) la Matrice Éthérique ;\nc) la Matrice Kétherique ;\nd) la Matrice Céleste ;\nd) la Matrice Je Suis.",
        "de": "a) Ka-Matrix;\nb) Ätherische Matrix;\nc) Ketherische Matrix;\nd) Himmlische Matrix;\nd) Ich-Bin-Matrix.",
        "it": "a) la Matrice Ka;\nb) la Matrice Eterica;\nc) la Matrice Keterica;\nd) la Matrice Celeste;\nd) la Matrice Io Sono.",
        "pl": "a) Matrycy Ka;\nb) Matrycy Eterycznej;\nc) Matrycy Keterycznej;\nd) Matrycy Niebiańskiej;\nd) Matrycy Jam Jest.",
        "tr": "a) Ka Matrisi;\nb) Eterik Matris;\nc) Keterik Matris;\nd) Göksel Matris;\nd) Ben-İm Matrisi.",
        "zh": "a) 卡矩阵；\nb) 以太矩阵；\nc) 王冠矩阵；\nd) 天界矩阵；\nd) 我是矩阵。",
        "ja": "a) カー・マトリックス；\nb) エーテル・マトリックス；\nc) ケセリック・マトリックス；\nd) 天のマトリックス；\nd) 「わたしはある」マトリックス。",
        "ko": "가) 카 매트릭스;\n나) 에테르 매트릭스;\n다) 케테르 매트릭스;\n라) 천상 매트릭스;\n라) '나는 있다' 매트릭스.",
        "hi": "क) का मैट्रिक्स;\nख) ईथरिक मैट्रिक्स;\nग) केथेरिक मैट्रिक्स;\nघ) आकाशीय मैट्रिक्स;\nघ) \"मैं हूँ\" मैट्रिक्स।",
        "bn": "ক) কা ম্যাট্রিক্স;\nখ) ইথেরিক ম্যাট্রিক্স;\nগ) কেথেরিক ম্যাট্রিক্স;\nঘ) স্বর্গীয় ম্যাট্রিক্স;\nঘ) \"আমি আছি\" ম্যাট্রিক্স।"
      ],
      "steplast": [
        "en": "Return to today, but continue to lie down for at least two hours.",
        "ru": "Возвращайтесь в сегодняшний день, но продолжайте лежать не менее двух часов.",
        "uk": "Повертайтеся в сьогоднішній день, але продовжуйте лежати не менше двох годин.",
        "es": "Regresa al día de hoy, pero permanece recostado al menos dos horas.",
        "pt": "Volte para o dia de hoje, mas continue deitado por pelo menos duas horas.",
        "fr": "Revenez à aujourd'hui, mais restez allongé au moins deux heures.",
        "de": "Kehre in das Heute zurück, bleibe aber noch mindestens zwei Stunden liegen.",
        "it": "Torna a oggi, ma resta sdraiato per almeno due ore.",
        "pl": "Wróć do dnia dzisiejszego, ale pozostań w pozycji leżącej przez co najmniej dwie godziny.",
        "tr": "Bugüne geri dön, ancak en az iki saat daha uzanmayı sürdür.",
        "zh": "回到今天，但请继续躺卧至少两个小时。",
        "ja": "今日へ戻ります。ただし、少なくとも2時間は横になったままでいてください。",
        "ko": "오늘로 돌아오되, 최소 두 시간은 그대로 누워 계세요.",
        "hi": "आज में लौट आएँ, पर कम से कम दो घंटे तक लेटे रहें।",
        "bn": "আজকের দিনে ফিরে আসুন, তবে অন্তত দুই ঘণ্টা শুয়ে থাকুন।"
      ],
      "part1step11": [
        "en": "Ask your Higher Self to clear, align, open, activate and fill the Hara line channels and chakras.",
        "ru": "Попросите свое Высшее Я очистить, выстроить, открыть, активировать и заполнить собой каналы и чакры линии Хара.",
        "uk": "Попросіть своє Вище Я очистити, вирівняти, відкрити, активувати та заповнити собою канали та чакри лінії Хара.",
        "es": "Pide a tu Yo Superior que limpie, alinee, abra, active y llene los canales y chakras de la línea Hara.",
        "pt": "Peça ao seu Eu Superior que limpe, alinhe, abra, ative e preencha os canais e chakras da linha Hara.",
        "fr": "Demandez à votre Soi Supérieur de nettoyer, aligner, ouvrir, activer et remplir les canaux et les chakras de la ligne Hara.",
        "de": "Bitte dein Höheres Selbst, die Kanäle und Chakren der Hara-Linie zu reinigen, auszurichten, zu öffnen, zu aktivieren und zu füllen.",
        "it": "Chiedi al tuo Sé Superiore di purificare, allineare, aprire, attivare e riempire i canali e i chakra della linea Hara.",
        "pl": "Poproś swoją Wyższą Jaźń o oczyszczenie, wyrównanie, otwarcie, aktywację i wypełnienie kanałów i czakr linii Hara.",
        "tr": "Yüksek Benliğinden Hara hattının kanallarını ve çakralarını arındırmasını, hizalamasını, açmasını, etkinleştirmesini ve doldurmasını iste.",
        "zh": "请你的高我清理、校准、打开、激活并充满哈拉线的通道与脉轮。",
        "ja": "ハイヤーセルフに、ハララインの通路とチャクラを浄化し、整え、開き、活性化し、満たすよう願い出ます。",
        "ko": "상위 자아에게 하라 라인의 통로와 차크라를 정화하고 정렬하며 열고 활성화하고 채워 달라고 청하세요.",
        "hi": "अपने उच्च स्व से प्रार्थना करें कि वह हारा रेखा के मार्गों और चक्रों को शुद्ध करे, संरेखित करे, खोले, सक्रिय करे और भर दे।",
        "bn": "আপনার উচ্চতর সত্তাকে বলুন হারা রেখার পথ ও চক্রগুলি শুদ্ধ করতে, সারিবদ্ধ করতে, খুলে দিতে, সক্রিয় করতে ও পূর্ণ করতে।"
      ],
      "part1step12": [
        "en": "Ask your Higher Self to clear, align, open, activate and fill the Kundalini channels and chakras.",
        "ru": "Попросите свое Высшее Я очистить, выстроить, открыть, активировать и заполнить собой каналы и чакры Кундалини.",
        "uk": "Попросіть своє Вище Я очистити, вирівняти, відкрити, активувати та заповнити собою канали та чакри Кундаліні.",
        "es": "Pide a tu Yo Superior que limpie, alinee, abra, active y llene los canales y chakras de la Kundalini.",
        "pt": "Peça ao seu Eu Superior que limpe, alinhe, abra, ative e preencha os canais e chakras da Kundalini.",
        "fr": "Demandez à votre Soi Supérieur de nettoyer, aligner, ouvrir, activer et remplir les canaux et les chakras de la Kundalini.",
        "de": "Bitte dein Höheres Selbst, die Kundalini-Kanäle und -Chakren zu reinigen, auszurichten, zu öffnen, zu aktivieren und zu füllen.",
        "it": "Chiedi al tuo Sé Superiore di purificare, allineare, aprire, attivare e riempire i canali e i chakra della Kundalini.",
        "pl": "Poproś swoją Wyższą Jaźń o oczyszczenie, wyrównanie, otwarcie, aktywację i wypełnienie kanałów i czakr Kundalini.",
        "tr": "Yüksek Benliğinden Kundalini kanallarını ve çakralarını arındırmasını, hizalamasını, açmasını, etkinleştirmesini ve doldurmasını iste.",
        "zh": "请你的高我清理、校准、打开、激活并充满昆达里尼的通道与脉轮。",
        "ja": "ハイヤーセルフに、クンダリーニの通路とチャクラを浄化し、整え、開き、活性化し、満たすよう願い出ます。",
        "ko": "상위 자아에게 쿤달리니의 통로와 차크라를 정화하고 정렬하며 열고 활성화하고 채워 달라고 청하세요.",
        "hi": "अपने उच्च स्व से प्रार्थना करें कि वह कुंडलिनी के मार्गों और चक्रों को शुद्ध करे, संरेखित करे, खोले, सक्रिय करे और भर दे।",
        "bn": "আপনার উচ্চতর সত্তাকে বলুন কুণ্ডলিনীর পথ ও চক্রগুলি শুদ্ধ করতে, সারিবদ্ধ করতে, খুলে দিতে, সক্রিয় করতে ও পূর্ণ করতে।"
      ],
      "part2step4": [
        "en": "Ask to restore, heal and activate your Silver Cord.",
        "ru": "Попросите восстановить, исцелить и активировать вашу Серебряную Нить.",
        "uk": "Попросіть відновити, зцілити та активувати вашу Срібну Нитку.",
        "es": "Pide que se restaure, sane y active tu Cordón de Plata.",
        "pt": "Peça para restaurar, curar e ativar seu Cordão de Prata.",
        "fr": "Demandez la restauration, la guérison et l'activation de votre Cordon d'Argent.",
        "de": "Bitte darum, deine Silberschnur wiederherzustellen, zu heilen und zu aktivieren.",
        "it": "Chiedi di ripristinare, guarire e attivare il tuo Cordone d'Argento.",
        "pl": "Poproś o przywrócenie, uzdrowienie i aktywację Twojego Srebrnego Sznura.",
        "tr": "Gümüş Kordonunun onarılmasını, iyileştirilmesini ve etkinleştirilmesini iste.",
        "zh": "请求修复、疗愈并激活你的银线。",
        "ja": "シルバーコードの修復・癒やし・活性化を願い出ます。",
        "ko": "은줄의 회복과 치유, 활성화를 청하세요.",
        "hi": "अपनी रजत डोर की पुनर्स्थापना, उपचार और सक्रियण की प्रार्थना करें।",
        "bn": "আপনার রৌপ্য রজ্জু পুনরুদ্ধার, নিরাময় ও সক্রিয় করার প্রার্থনা করুন।"
      ],
      "part2step5": [
        "en": "Ask your Higher Self to come to you.",
        "ru": "Попросите свое Высшее Я явиться к вам.",
        "uk": "Попросіть своє Вище Я явитися до вас.",
        "es": "Pide a tu Yo Superior que venga a ti.",
        "pt": "Peça ao seu Eu Superior que venha até você.",
        "fr": "Demandez à votre Soi Supérieur de venir à vous.",
        "de": "Bitte dein Höheres Selbst, zu dir zu kommen.",
        "it": "Chiedi al tuo Sé Superiore di venire da te.",
        "pl": "Poproś swoją Wyższą Jaźń, aby przyszła do Ciebie.",
        "tr": "Yüksek Benliğinden sana gelmesini iste.",
        "zh": "请你的高我来到你身边。",
        "ja": "ハイヤーセルフに来てもらうよう願い出ます。",
        "ko": "상위 자아에게 당신에게 와 달라고 청하세요.",
        "hi": "अपने उच्च स्व से अपने पास आने की प्रार्थना करें।",
        "bn": "আপনার উচ্চতর সত্তাকে আপনার কাছে আসতে বলুন।"
      ],
      "part2step8": [
        "en": "Ask to clear, heal, align, open and activate the three Galactic Matrices.",
        "ru": "Попросите очистить, исцелить, выстроить, открыть и активировать три Галактические Матрицы.",
        "uk": "Попросіть очистити, зцілити, вирівняти, відкрити та активувати три Галактичні Матриці.",
        "es": "Pide que se limpien, sanen, alineen, abran y activen las tres Matrices Galácticas.",
        "pt": "Peça para limpar, curar, alinhar, abrir e ativar as três Matrizes Galácticas.",
        "fr": "Demandez le nettoyage, la guérison, l'alignement, l'ouverture et l'activation des trois Matrices Galactiques.",
        "de": "Bitte darum, die drei Galaktischen Matrizen zu reinigen, zu heilen, auszurichten, zu öffnen und zu aktivieren.",
        "it": "Chiedi di purificare, guarire, allineare, aprire e attivare le tre Matrici Galattiche.",
        "pl": "Poproś o oczyszczenie, uzdrowienie, wyrównanie, otwarcie i aktywację trzech Matryc Galaktycznych.",
        "tr": "Üç Galaktik Matrisin arındırılmasını, iyileştirilmesini, hizalanmasını, açılmasını ve etkinleştirilmesini iste.",
        "zh": "请求清理、疗愈、校准、打开并激活三个银河矩阵。",
        "ja": "3つの銀河マトリックスの浄化・癒やし・整列・開放・活性化を願い出ます。",
        "ko": "세 개의 은하 매트릭스를 정화하고 치유하며 정렬하고 열어 활성화해 달라고 청하세요.",
        "hi": "तीनों आकाशगंगीय मैट्रिक्स को शुद्ध करने, उपचार करने, संरेखित करने, खोलने और सक्रिय करने की प्रार्थना करें।",
        "bn": "তিনটি ছায়াপথীয় ম্যাট্রিক্স শুদ্ধ, নিরাময়, সারিবদ্ধ, উন্মুক্ত ও সক্রিয় করার প্রার্থনা করুন।"
      ],
      "part2step9": [
        "en": "Ask to clear, heal, align, open and activate the five Galactic Chakras.",
        "ru": "Попросите очистить, исцелить, выстроить, открыть и активировать пять Галактических Чакр.",
        "uk": "Попросіть очистити, зцілити, вирівняти, відкрити та активувати п'ять Галактичних Чакр.",
        "es": "Pide que se limpien, sanen, alineen, abran y activen los cinco Chakras Galácticos.",
        "pt": "Peça para limpar, curar, alinhar, abrir e ativar os cinco Chakras Galácticos.",
        "fr": "Demandez le nettoyage, la guérison, l'alignement, l'ouverture et l'activation des cinq Chakras Galactiques.",
        "de": "Bitte darum, die fünf Galaktischen Chakren zu reinigen, zu heilen, auszurichten, zu öffnen und zu aktivieren.",
        "it": "Chiedi di purificare, guarire, allineare, aprire e attivare i cinque Chakra Galattici.",
        "pl": "Poproś o oczyszczenie, uzdrowienie, wyrównanie, otwarcie i aktywację pięciu Czakr Galaktycznych.",
        "tr": "Beş Galaktik Çakranın arındırılmasını, iyileştirilmesini, hizalanmasını, açılmasını ve etkinleştirilmesini iste.",
        "zh": "请求清理、疗愈、校准、打开并激活五个银河脉轮。",
        "ja": "5つの銀河チャクラの浄化・癒やし・整列・開放・活性化を願い出ます。",
        "ko": "다섯 개의 은하 차크라를 정화하고 치유하며 정렬하고 열어 활성화해 달라고 청하세요.",
        "hi": "पाँचों आकाशगंगीय चक्रों को शुद्ध करने, उपचार करने, संरेखित करने, खोलने और सक्रिय करने की प्रार्थना करें।",
        "bn": "পাঁচটি ছায়াপথীয় চক্র শুদ্ধ, নিরাময়, সারিবদ্ধ, উন্মুক্ত ও সক্রিয় করার প্রার্থনা করুন।"
      ],
      "part2step10": [
        "en": "Ask your Essence Self/Star Self to come forth and merge with your Higher Self.",
        "ru": "Попросите свое Сущностное Я/Звездное Я явиться и слиться с вашим Высшим Я.",
        "uk": "Попросіть своє Сутнісне Я/Зоряне Я явитися та злитися з вашим Вищим Я.",
        "es": "Pide a tu Yo Esencial/Yo Estelar que se manifieste y se fusione con tu Yo Superior.",
        "pt": "Peça ao seu Eu Essencial/Eu Estelar que se manifeste e se funda com o seu Eu Superior.",
        "fr": "Demandez à votre Soi Essentiel / Soi Stellaire de se manifester et de fusionner avec votre Soi Supérieur.",
        "de": "Bitte dein Essenzielles Selbst / Stern-Selbst, hervorzutreten und mit deinem Höheren Selbst zu verschmelzen.",
        "it": "Chiedi al tuo Sé Essenziale/Sé Stellare di farsi avanti e fondersi con il tuo Sé Superiore.",
        "pl": "Poproś swoją Istotową Jaźń/Gwiezdną Jaźń, aby się ujawniła i połączyła z Twoją Wyższą Jaźnią.",
        "tr": "Özsel Benliğinden/Yıldız Benliğinden öne çıkmasını ve Yüksek Benliğinle birleşmesini iste.",
        "zh": "请你的本质自我／星际自我显现，并与你的高我融合。",
        "ja": "本質の自己／スターセルフに現れてもらい、ハイヤーセルフと融合するよう願い出ます。",
        "ko": "본질 자아/별의 자아에게 나타나 상위 자아와 하나가 되어 달라고 청하세요.",
        "hi": "अपने सारभूत स्व/तारा स्व से प्रार्थना करें कि वह प्रकट हो और आपके उच्च स्व में विलीन हो जाए।",
        "bn": "আপনার সারসত্তা/তারা-সত্তাকে বলুন প্রকাশিত হয়ে আপনার উচ্চতর সত্তার সঙ্গে মিলিত হতে।"
      ],
      "part2step11": [
        "en": "Talk to him a little and ask him to connect with you forever.",
        "ru": "Поговорите с ним немного и попросите соединиться с вами навсегда.",
        "uk": "Поспілкуйтеся з ним трохи та попросіть з'єднатися з вами назавжди.",
        "es": "Habla un poco con él y pídele que se conecte contigo para siempre.",
        "pt": "Converse um pouco com ele e peça que se conecte a você para sempre.",
        "fr": "Parlez-lui un peu et demandez-lui de se relier à vous pour toujours.",
        "de": "Sprich ein wenig mit ihm und bitte es, sich für immer mit dir zu verbinden.",
        "it": "Parlagli un po' e chiedigli di legarsi a te per sempre.",
        "pl": "Porozmawiaj z nią chwilę i poproś, aby połączyła się z Tobą na zawsze.",
        "tr": "Onunla biraz konuş ve sonsuza dek seninle bağ kurmasını iste.",
        "zh": "与他交谈片刻，并请他永远与你相连。",
        "ja": "少し語りかけ、永遠にあなたとつながってくれるよう頼みます。",
        "ko": "잠시 이야기를 나누고, 영원히 당신과 이어져 달라고 청하세요.",
        "hi": "उससे थोड़ी बात करें और प्रार्थना करें कि वह सदा के लिए आपसे जुड़ जाए।",
        "bn": "তাঁর সঙ্গে কিছুক্ষণ কথা বলুন এবং চিরকালের জন্য আপনার সঙ্গে যুক্ত হতে বলুন।"
      ],
      "part3step11": [
        "en": "Ask to clear, heal, align, open and activate the three Matrices of the causal body.",
        "ru": "Попросите очистить, исцелить, выстроить, открыть и активировать три Матрицы каузального тела.",
        "uk": "Попросіть очистити, зцілити, вистроїти, відкрити та активувати три Матриці каузального тіла.",
        "es": "Pide que se limpien, sanen, alineen, abran y activen las tres Matrices del cuerpo causal.",
        "pt": "Peça para limpar, curar, alinhar, abrir e ativar as três Matrizes do corpo causal.",
        "fr": "Demandez le nettoyage, la guérison, l'alignement, l'ouverture et l'activation des trois Matrices du corps causal.",
        "de": "Bitte darum, die drei Matrizen des Kausalkörpers zu reinigen, zu heilen, auszurichten, zu öffnen und zu aktivieren.",
        "it": "Chiedi di purificare, guarire, allineare, aprire e attivare le tre Matrici del corpo causale.",
        "pl": "Poproś o oczyszczenie, uzdrowienie, wyrównanie, otwarcie i aktywację trzech Matryc ciała przyczynowego.",
        "tr": "Nedensel bedenin üç Matrisinin arındırılmasını, iyileştirilmesini, hizalanmasını, açılmasını ve etkinleştirilmesini iste.",
        "zh": "请求清理、疗愈、校准、打开并激活因果体的三个矩阵。",
        "ja": "原因体の3つのマトリックスの浄化・癒やし・整列・開放・活性化を願い出ます。",
        "ko": "원인체의 세 매트릭스를 정화하고 치유하며 정렬하고 열어 활성화해 달라고 청하세요.",
        "hi": "कारण शरीर के तीनों मैट्रिक्स को शुद्ध करने, उपचार करने, संरेखित करने, खोलने और सक्रिय करने की प्रार्थना करें।",
        "bn": "কারণ শরীরের তিনটি ম্যাট্রিক্স শুদ্ধ, নিরাময়, সারিবদ্ধ, উন্মুক্ত ও সক্রিয় করার প্রার্থনা করুন।"
      ],
      "part3step12": [
        "en": "Ask to clear, heal, align, open and activate the five chakras of the causal body.",
        "ru": "Попросите очистить, исцелить, выстроить, открыть и активировать пять чакр каузального тела.",
        "uk": "Попросіть очистити, зцілити, вистроїти, відкрити та активувати п'ять чакр каузального тіла.",
        "es": "Pide que se limpien, sanen, alineen, abran y activen los cinco chakras del cuerpo causal.",
        "pt": "Peça para limpar, curar, alinhar, abrir e ativar os cinco chakras do corpo causal.",
        "fr": "Demandez le nettoyage, la guérison, l'alignement, l'ouverture et l'activation des cinq chakras du corps causal.",
        "de": "Bitte darum, die fünf Chakren des Kausalkörpers zu reinigen, zu heilen, auszurichten, zu öffnen und zu aktivieren.",
        "it": "Chiedi di purificare, guarire, allineare, aprire e attivare i cinque chakra del corpo causale.",
        "pl": "Poproś o oczyszczenie, uzdrowienie, wyrównanie, otwarcie i aktywację pięciu czakr ciała przyczynowego.",
        "tr": "Nedensel bedenin beş çakrasının arındırılmasını, iyileştirilmesini, hizalanmasını, açılmasını ve etkinleştirilmesini iste.",
        "zh": "请求清理、疗愈、校准、打开并激活因果体的五个脉轮。",
        "ja": "原因体の5つのチャクラの浄化・癒やし・整列・開放・活性化を願い出ます。",
        "ko": "원인체의 다섯 차크라를 정화하고 치유하며 정렬하고 열어 활성화해 달라고 청하세요.",
        "hi": "कारण शरीर के पाँचों चक्रों को शुद्ध करने, उपचार करने, संरेखित करने, खोलने और सक्रिय करने की प्रार्थना करें।",
        "bn": "কারণ শরীরের পাঁচটি চক্র শুদ্ধ, নিরাময়, সারিবদ্ধ, উন্মুক্ত ও সক্রিয় করার প্রার্থনা করুন।"
      ],
      "part3step13": [
        "en": "Ask your Divine Self/OverSoul to come and merge with your Higher Self and Essential Self.",
        "ru": "Попросите свое Божественное Я/Сверхдушу прийти и слиться с вашим Высшим Я и Сущностным Я.",
        "uk": "Попросіть своє Божественне Я/Наддушу прийти та злитися з вашим Вищим Я та Сутнісним Я.",
        "es": "Pide a tu Yo Divino/Superalma que venga y se fusione con tu Yo Superior y tu Yo Esencial.",
        "pt": "Peça ao seu Eu Divino/Superalma que venha e se funda com o seu Eu Superior e o seu Eu Essencial.",
        "fr": "Demandez à votre Soi Divin / Sur-âme de venir et de fusionner avec votre Soi Supérieur et votre Soi Essentiel.",
        "de": "Bitte dein Göttliches Selbst / deine Überseele, zu kommen und mit deinem Höheren Selbst und deinem Essenziellen Selbst zu verschmelzen.",
        "it": "Chiedi al tuo Sé Divino/Anima Superiore di venire e fondersi con il tuo Sé Superiore e il tuo Sé Essenziale.",
        "pl": "Poproś swoją Boską Jaźń/Nadduszę, aby przyszła i połączyła się z Twoją Wyższą Jaźnią i Istotową Jaźnią.",
        "tr": "İlahi Benliğinden/Üst Ruhundan gelmesini ve Yüksek Benliğin ile Özsel Benliğinle birleşmesini iste.",
        "zh": "请你的神圣自我／超灵前来，与你的高我和本质自我融合。",
        "ja": "神聖なる自己／オーバーソウルに来てもらい、ハイヤーセルフと本質の自己と融合するよう願い出ます。",
        "ko": "신성한 자아/오버소울에게 와서 상위 자아 및 본질 자아와 하나가 되어 달라고 청하세요.",
        "hi": "अपने दिव्य स्व/परम आत्मा से प्रार्थना करें कि वह आकर आपके उच्च स्व और सारभूत स्व में विलीन हो जाए।",
        "bn": "আপনার দিব্য সত্তা/পরমাত্মাকে বলুন এসে আপনার উচ্চতর সত্তা ও সারসত্তার সঙ্গে মিলিত হতে।"
      ],
      "part3step14": [
        "en": "Ask his name, talk to him.",
        "ru": "Спросите его имя, поговорите с ним.",
        "uk": "Запитайте його ім'я, поспілкуйтеся з ним.",
        "es": "Pregúntale su nombre y habla con él.",
        "pt": "Pergunte o nome dele e converse com ele.",
        "fr": "Demandez-lui son nom, parlez-lui.",
        "de": "Frage nach seinem Namen, sprich mit ihm.",
        "it": "Chiedigli il suo nome, parla con lui.",
        "pl": "Zapytaj o jej imię, porozmawiaj z nią.",
        "tr": "Adını sor, onunla konuş.",
        "zh": "询问他的名字，与他交谈。",
        "ja": "名前を尋ね、語りかけます。",
        "ko": "이름을 묻고, 이야기를 나누세요.",
        "hi": "उसका नाम पूछें, उससे बात करें।",
        "bn": "তাঁর নাম জিজ্ঞাসা করুন, তাঁর সঙ্গে কথা বলুন।"
      ],
      "part3step15": [
        "en": "Ask your Divine Self to stay with you forever (the process may take several days).",
        "ru": "Попросите свое Божественное Я остаться с вами навсегда (процесс может длиться несколько дней).",
        "uk": "Попросіть своє Божественне Я залишитися з вами назавжди (процес може тривати кілька днів).",
        "es": "Pide a tu Yo Divino que permanezca contigo para siempre (el proceso puede durar varios días).",
        "pt": "Peça ao seu Eu Divino que fique com você para sempre (o processo pode levar vários dias).",
        "fr": "Demandez à votre Soi Divin de rester avec vous pour toujours (le processus peut prendre plusieurs jours).",
        "de": "Bitte dein Göttliches Selbst, für immer bei dir zu bleiben (der Prozess kann mehrere Tage dauern).",
        "it": "Chiedi al tuo Sé Divino di restare con te per sempre (il processo può richiedere diversi giorni).",
        "pl": "Poproś swoją Boską Jaźń, aby została z Tobą na zawsze (proces może potrwać kilka dni).",
        "tr": "İlahi Benliğinden sonsuza dek seninle kalmasını iste (bu süreç birkaç gün sürebilir).",
        "zh": "请你的神圣自我永远与你同在（这个过程可能需要数日）。",
        "ja": "神聖なる自己に、永遠にそばにいてくれるよう願い出ます（このプロセスには数日かかることがあります）。",
        "ko": "신성한 자아에게 영원히 함께 있어 달라고 청하세요 (이 과정은 며칠이 걸릴 수 있습니다).",
        "hi": "अपने दिव्य स्व से प्रार्थना करें कि वह सदा आपके साथ रहे (इस प्रक्रिया में कई दिन लग सकते हैं)।",
        "bn": "আপনার দিব্য সত্তাকে চিরকাল আপনার সঙ্গে থাকতে বলুন (এই প্রক্রিয়ায় কয়েক দিন লাগতে পারে)।"
      ],
      "part3step16": [
        "en": "Invite your Goddess to come into you and merge with your Divine Self, and also connect your energy with the energy of all your bodies. Talk to her, ask her name.",
        "ru": "Пригласите свою Богиню войти в вас и слиться с вашим Божественным Я, а также соединить свою энергию с энергией всех ваших тел. Поговорите с ней, спросите ее имя.",
        "uk": "Запросіть свою Богиню ввійти до вас та злитися з вашим Божественним Я, а також з'єднати свою енергію з енергією всіх ваших тіл. Поспілкуйтеся з нею, запитайте її ім'я.",
        "es": "Invita a tu Diosa a entrar en ti y fusionarse con tu Yo Divino, y a unir también su energía con la de todos tus cuerpos. Habla con ella y pregúntale su nombre.",
        "pt": "Convide sua Deusa a entrar em você e se fundir com o seu Eu Divino, e também a unir a energia dela à energia de todos os seus corpos. Converse com ela e pergunte o nome dela.",
        "fr": "Invitez votre Déesse à entrer en vous et à fusionner avec votre Soi Divin, et à relier aussi son énergie à celle de tous vos corps. Parlez-lui, demandez-lui son nom.",
        "de": "Lade deine Göttin ein, in dich zu kommen und mit deinem Göttlichen Selbst zu verschmelzen und ihre Energie mit der Energie all deiner Körper zu verbinden. Sprich mit ihr, frage sie nach ihrem Namen.",
        "it": "Invita la tua Dea a entrare in te e a fondersi con il tuo Sé Divino, e a unire la sua energia a quella di tutti i tuoi corpi. Parla con lei, chiedile il suo nome.",
        "pl": "Zaproś swoją Boginię, aby weszła w Ciebie i połączyła się z Twoją Boską Jaźnią, a także połączyła swoją energię z energią wszystkich Twoich ciał. Porozmawiaj z nią, zapytaj o jej imię.",
        "tr": "Tanrıçanı içine gelmeye ve İlahi Benliğinle birleşmeye, ayrıca enerjisini tüm bedenlerinin enerjisiyle bağlamaya davet et. Onunla konuş, adını sor.",
        "zh": "邀请你的女神进入你之中，与你的神圣自我融合，并将她的能量与你所有身体的能量相连。与她交谈，询问她的名字。",
        "ja": "あなたの女神を招き入れ、神聖なる自己と融合し、そのエネルギーをすべての体のエネルギーとつなげてもらいます。語りかけ、名前を尋ねましょう。",
        "ko": "당신의 여신을 초대해 안으로 들어와 신성한 자아와 하나가 되고, 그 에너지를 당신의 모든 몸의 에너지와 이어 달라고 하세요. 이야기를 나누고 이름을 물으세요.",
        "hi": "अपनी देवी को आमंत्रित करें कि वे आप में आएँ और आपके दिव्य स्व में विलीन हों, तथा अपनी ऊर्जा को आपके सभी शरीरों की ऊर्जा से जोड़ें। उनसे बात करें, उनका नाम पूछें।",
        "bn": "আপনার দেবীকে আহ্বান করুন যেন তিনি আপনার ভিতরে আসেন ও আপনার দিব্য সত্তার সঙ্গে মিলিত হন, আর তাঁর শক্তিকে আপনার সমস্ত দেহের শক্তির সঙ্গে যুক্ত করেন। তাঁর সঙ্গে কথা বলুন, নাম জিজ্ঞাসা করুন।"
      ],
      "part3step17": [
        "en": "Ask that the process just completed become permanent.",
        "ru": "Попросите, чтобы только что завершенный процесс приобрел постоянный характер.",
        "uk": "Попросіть, щоб щойно завершений процес набув постійного характеру.",
        "es": "Pide que el proceso que acabas de completar sea permanente.",
        "pt": "Peça que o processo recém-concluído se torne permanente.",
        "fr": "Demandez que le processus qui vient d'être accompli devienne permanent.",
        "de": "Bitte darum, dass der soeben abgeschlossene Prozess dauerhaft wird.",
        "it": "Chiedi che il processo appena completato diventi permanente.",
        "pl": "Poproś, aby właśnie zakończony proces stał się trwały.",
        "tr": "Az önce tamamlanan sürecin kalıcı olmasını iste.",
        "zh": "请求刚刚完成的过程成为永久的。",
        "ja": "いま完了したプロセスが恒久的なものになるよう願い出ます。",
        "ko": "방금 마친 과정이 영구적으로 유지되도록 청하세요.",
        "hi": "प्रार्थना करें कि अभी पूरी हुई प्रक्रिया स्थायी हो जाए।",
        "bn": "এইমাত্র সম্পন্ন প্রক্রিয়াটি যেন স্থায়ী হয়, তা প্রার্থনা করুন।"
      ],
      "paused": [
        "en": "Paused",
        "ru": "Пауза",
        "uk": "Пауза",
        "es": "En pausa",
        "pt": "Pausado",
        "fr": "En pause",
        "de": "Pausiert",
        "it": "In pausa",
        "pl": "Wstrzymane",
        "tr": "Duraklatıldı",
        "zh": "已暂停",
        "ja": "一時停止中",
        "ko": "일시 정지됨",
        "hi": "रुका हुआ",
        "bn": "থামানো"
      ],
      "pause": [
        "en": "Pause",
        "ru": "Пауза",
        "uk": "Пауза",
        "es": "Pausar",
        "pt": "Pausar",
        "fr": "Pause",
        "de": "Pause",
        "it": "Pausa",
        "pl": "Wstrzymaj",
        "tr": "Duraklat",
        "zh": "暂停",
        "ja": "一時停止",
        "ko": "일시 정지",
        "hi": "रोकें",
        "bn": "থামান"
      ],
      "resume": [
        "en": "Resume",
        "ru": "Продолжить",
        "uk": "Продовжити",
        "es": "Reanudar",
        "pt": "Retomar",
        "fr": "Reprendre",
        "de": "Fortsetzen",
        "it": "Riprendi",
        "pl": "Wznów",
        "tr": "Sürdür",
        "zh": "继续",
        "ja": "再開",
        "ko": "다시 시작",
        "hi": "जारी रखें",
        "bn": "আবার শুরু"
      ]
    ]
    
    if let languageTranslations = translations[self],
       let translation = languageTranslations[languageCode] {
      return translation
    }
    
    // Fallback to original string
    return self
  }
}
